version: '3.6'

services:
   mongodb:
     image: mongo
     environment:
       MONGO_INITDB_ROOT_USERNAME: usrCensusApp
       MONGO_INITDB_ROOT_PASSWORD: 1025@1064
       MONGO_INITDB_DATABASE: dbCensusApp
     restart: always
     volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
     ports: 
        - "27017:27017"