version: '3.0'

services:
   mongodb:
     image: mongo
     environment:
       MONGO_INITDB_ROOT_USERNAME: balta
       MONGO_INITDB_ROOT_PASSWORD: e296cd9f 
     restart: always
     ports: 
        - "27017:27017"

   myapp:
     depends_on:
       - mongodb
     image: aspnetapp
     build:
       context: .
     ports:
       - "8080:80"