version: '3.6'

services:
   mongodb:
     image: mongo
     environment:
       MONGO_INITDB_ROOT_USERNAME: usrCensusApp
       MONGO_INITDB_ROOT_PASSWORD: z1x2c3v4b5n6m7
       MONGO_INITDB_DATABASE: dbCensusApp
     restart: always
     container_name: mongoDb
     hostname: mongoDb
     volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
     networks:
        - mongodb_network
     ports: 
        - "27017:27017"
   censusApp:
     depends_on:
       - mongodb
     image: censusapp
     environment:
        ASPNETCORE_URLS: https://+:443;http://+:80
        ASPNETCORE_Kestrel__Certificates__Default__Password: dotnethttps
        ASPNETCORE_Kestrel__Certificates__Default__Path: /mnt/https/aspnetapp.pfx 
     restart: always
     container_name: censusApp
     hostname: censusapp
     volumes:
        - ./aspnetapp.pfx:/mnt/https/aspnetapp.pfx
     build:
       context: src/CensusApp.Api/
     networks:
        - mongodb_network
     ports:
       - "8080:80"
       - "8081:443"
   frontend:
     depends_on:
       - censusApp
     image: censusappfrontend
     restart: always
     container_name: censusAppFrontEnd
     build:
       context: ../census-app-frontend
     networks:
        - mongodb_network
     ports:
       - "80:80"
networks:
    mongodb_network:
          name: mongodb_network
          driver: bridge