name: CI/CD para aplicação CensusApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master     

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore
      run: dotnet restore src/

    - name: Build 
      run: dotnet build src/ --configuration Release
    
    - name: Test 
      run: dotnet test src/CensusApp.Test
    
    - name: Docker compose Up
      run: docker-compose -f docker-compose-ci.yml up --build -d  

    - name: Install Newman
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g newman

    - name: Run request tests
      run: newman run integra/census-app-integra.postman_collection.json
    
    - name: Docker compose Down
      run: docker-compose -f docker-compose-ci.yml down 

   

